import 'dart:io';
import 'dart:typed_data';

import 'package:ratel_orm/postgres.dart';
import 'package:ratel_orm/ratel_orm.dart';
import 'package:test/test.dart';

import '../support/fixtures/entities/counter.dart';
import '../support/fixtures/entities/gadget.dart';
import '../support/fixtures/entities/gadget_kind.dart';
import '../support/fixtures/entities/user_account.dart';
import '../support/fixtures/repositories/counter_repository.dart';
import '../support/fixtures/repositories/gadget_repository.dart';
import '../support/fixtures/repositories/user_account_repository.dart';
import '../support/test_entities.dart';

void main() {
  TestEntities.install();

  final skip = Platform.environment['DB_HOST'] == null
      ? 'set DB_HOST/DB_NAME/DB_USER/DB_PASSWORD to run the Postgres integration'
      : false;
  const gadgetsTable = 'CREATE TABLE gadgets ('
      'id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, '
      'display_name text NOT NULL, '
      'kind text NOT NULL, '
      'active boolean NOT NULL, '
      'price numeric(10, 2) NOT NULL, '
      'created_at timestamptz NOT NULL, '
      'note text, '
      'payload bytea)';
  const accountsTable = 'CREATE TABLE user_account ('
      'user_id bigint PRIMARY KEY, '
      'email_address text NOT NULL, '
      'last_login_at timestamp)';
  const countersTable = 'CREATE TABLE counters ('
      'id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY)';
  final createdAt = DateTime.utc(2024, 5, 6, 7, 8, 9, 10);
  const slow = Duration(seconds: 10);

  Gadget lamp() => Gadget(
        name: 'lamp',
        kind: GadgetKind.toy,
        active: true,
        price: 9.5,
        createdAt: createdAt.toLocal(),
        note: 'fragile',
        payload: Uint8List.fromList([1, 2, 3]),
        selected: true,
      );

  Gadget fan({int? id}) => Gadget(
        id: id,
        name: 'fan',
        kind: GadgetKind.tool,
        active: false,
        price: 12.25,
        createdAt: DateTime.utc(2025, 1, 2),
      );

  group('RatelRepository against a live Postgres server', () {
    late PostgresDriver driver;
    late GadgetRepository gadgets;

    Future<void> dropTables() async {
      await driver.query('DROP TABLE IF EXISTS gadgets');
      await driver.query('DROP TABLE IF EXISTS user_account');
      await driver.query('DROP TABLE IF EXISTS counters');
    }

    setUp(() async {
      driver = PostgresDriver.fromEnv();
      await driver.open();
      await dropTables();
      await driver.query(gadgetsTable);
      await driver.query(accountsTable);
      await driver.query(countersTable);
      gadgets = GadgetRepository(driver);
    });

    tearDown(() async {
      await dropTables();
      await driver.close();
    });

    test('insert generates the id and maps every value back', () async {
      final stored = await gadgets.insert(lamp());
      expect(stored.id, isNotNull);
      expect(stored.name, 'lamp');
      expect(stored.kind, GadgetKind.toy);
      expect(stored.active, isTrue);
      expect(stored.price, 9.5);
      expect(stored.createdAt.isAtSameMomentAs(createdAt), isTrue);
      expect(stored.note, 'fragile');
      expect(stored.payload, [1, 2, 3]);
      expect(stored.selected, isFalse);

      final next = await gadgets.insert(lamp());
      expect(next.id, greaterThan(stored.id!));
    });

    test('stores values in their Postgres types', () async {
      await gadgets.insert(lamp());
      final raw = await driver.query(
        'SELECT kind, active, price, created_at FROM gadgets',
      );
      final row = raw.rows.single;
      expect(row['kind'], 'toy');
      expect(row['active'], isTrue);
      expect(row['price'], '9.50');
      expect(row['created_at'], isA<DateTime>());
    });

    test('nullable columns round-trip as null', () async {
      final stored = await gadgets.insert(fan());
      expect(stored.note, isNull);
      expect(stored.payload, isNull);

      final found = await gadgets.findById(stored.id!);
      expect(found?.name, 'fan');
      expect(found?.price, 12.25);
      expect(found?.note, isNull);
      expect(await gadgets.findById(stored.id! + 100), isNull);
    });

    test('update writes every column and yields null for a missing row',
        () async {
      final stored = await gadgets.insert(lamp());
      final updated = await gadgets.update(fan(id: stored.id));
      expect(updated?.id, stored.id);
      expect(updated?.name, 'fan');
      expect(updated?.kind, GadgetKind.tool);
      expect(updated?.active, isFalse);
      expect(updated?.payload, isNull);
      expect(updated?.createdAt, DateTime.utc(2025, 1, 2));

      expect(await gadgets.update(fan(id: stored.id! + 100)), isNull);
      expect(await gadgets.findAll(), hasLength(1));
    });

    test('deleteById reports whether a row was removed', () async {
      final stored = await gadgets.insert(lamp());
      expect(await gadgets.deleteById(stored.id!), isTrue);
      expect(await gadgets.deleteById(stored.id!), isFalse);
      expect(await gadgets.findAll(), isEmpty);
    });

    test('a set id is always inserted, under default names', () async {
      final accounts = UserAccountRepository(driver);
      final stored = await accounts.insert(UserAccount(
        userID: 40,
        emailAddress: 'ada@example.com',
        lastLoginAt: createdAt,
      ));
      expect(stored.userID, 40);
      expect(stored.lastLoginAt?.isAtSameMomentAs(createdAt), isTrue);
      expect((await accounts.findById(40))?.emailAddress, 'ada@example.com');
    });

    test('a local DateTime keeps its instant in a timestamp column', () async {
      final accounts = UserAccountRepository(driver);
      final local = createdAt.toLocal();
      await accounts.insert(UserAccount(
        userID: 41,
        emailAddress: 'ada@example.com',
        lastLoginAt: local,
      ));

      final found = await accounts.findById(41);
      expect(found?.lastLoginAt?.isAtSameMomentAs(createdAt), isTrue);

      final matched = await accounts.execute(
        'SELECT * FROM user_account WHERE last_login_at = @at',
        parameters: {'at': local},
      );
      expect([for (final account in matched) account.userID], [41]);
    });

    test('an entity with only an id works on a GENERATED ALWAYS identity',
        () async {
      final counters = CounterRepository(driver);
      final stored = await counters.insert(const Counter());
      expect(stored.id, isNotNull);
      expect((await counters.update(stored))?.id, stored.id);
      expect(await counters.update(Counter(id: stored.id! + 100)), isNull);
      expect(await counters.deleteById(stored.id!), isTrue);
    });

    test('find and execute map rows and yield an empty list for none',
        () async {
      await gadgets.insert(lamp());
      await gadgets.insert(fan());

      final toys =
          await gadgets.find(Query.from('gadgets').where('kind', '=', 'toy'));
      expect([for (final gadget in toys) gadget.name], ['lamp']);

      final pricey = await gadgets.execute(
        'SELECT * FROM gadgets WHERE price > @min',
        parameters: {'min': 100},
      );
      expect(pricey, isEmpty);
    });

    group('inside driver.transaction', () {
      test('a repository write rolls back with the transaction', () async {
        await expectLater(
          driver.transaction((session) async {
            await gadgets.insert(lamp());
            throw StateError('undo');
          }),
          throwsStateError,
        );
        expect(await gadgets.findAll(), isEmpty);
      });

      test('a repository sees what the transaction wrote', () async {
        final (all, stored, total) = await driver.transaction((session) async {
          await session.query(
            'INSERT INTO gadgets '
            '(display_name, kind, active, price, created_at) '
            'VALUES (@name, @kind, false, 1, @at)',
            parameters: {'name': 'fan', 'kind': 'tool', 'at': createdAt},
          );
          final stored = await gadgets.insert(lamp());
          final count =
              await session.query('SELECT count(*) AS total FROM gadgets');
          return (await gadgets.findAll(), stored, count.rows.single['total']);
        }).timeout(slow);
        expect([for (final gadget in all) gadget.name], ['fan', 'lamp']);
        expect(total, 2);
        expect((await gadgets.findById(stored.id!))?.name, 'lamp');
      });

      test('a repository updates a row the transaction has locked', () async {
        final stored = await gadgets.insert(lamp());
        final updated = await driver.transaction((session) async {
          await session.query(
            'UPDATE gadgets SET note = @note WHERE id = @id',
            parameters: {'note': 'locked', 'id': stored.id},
          );
          return gadgets.update(fan(id: stored.id));
        }).timeout(slow);
        expect(updated?.name, 'fan');
        expect((await gadgets.findById(stored.id!))?.name, 'fan');
      });

      test('a pool of one connection does not wait on itself', () async {
        final single = PostgresDriver(
          host: driver.host,
          port: driver.port,
          databaseName: driver.databaseName,
          username: driver.username,
          password: driver.password,
          sslMode: driver.sslMode,
          maxConnections: 1,
        );
        await single.open();
        try {
          final repository = GadgetRepository(single);
          final found = await single.transaction((session) async {
            await repository.insert(lamp());
            return repository.findAll();
          }).timeout(slow);
          expect(found, hasLength(1));
          expect(await repository.findAll(), hasLength(1));
        } finally {
          await single.close();
        }
      });

      test('a query that outlives the transaction runs on the pool', () async {
        late Future<List<Gadget>> afterwards;
        await driver.transaction((session) async {
          await gadgets.insert(lamp());
          afterwards = Future<void>.delayed(const Duration(milliseconds: 50))
              .then((_) => gadgets.findAll());
        });
        expect(await afterwards.timeout(slow), hasLength(1));
      });
    });
  }, skip: skip);
}
