include: package:lints/recommended.yaml

analyzer:
  errors:
    avoid_print: warning
    empty_catches: warning
  exclude:
    - "**/*.ratel.dart"

linter:
  rules:
    - avoid_print
    - empty_catches
    - curly_braces_in_flow_control_structures
