import '../driver/query_result.dart';
import '../driver/ratel_driver.dart';
import '../exceptions/mapping_exception.dart';
import '../exceptions/query_execution_exception.dart';
import '../query/built_query.dart';
import '../query/query.dart';
import '../runtime/entity_catalog.dart';
import '../runtime/entity_mapping.dart';
import '../runtime/entity_row.dart';
import '../runtime/ratel_orm_runtime.dart';
import 'entity_statements.dart';

abstract class RatelRepository<T extends Object, ID extends Object> {
  RatelRepository(this.driver) {
    _entity = _resolve();
  }

  final RatelDriver driver;

  late final EntityMapping _entity;

  String get table => _entity.table;

  Future<List<T>> findAll() async {
    final result =
        await _run(EntityStatements.selectAll(driver.dialect, _entity));
    return _mapAll(result);
  }

  Future<T?> findById(ID id) => _findById(id);

  Future<T> insert(T entity) async {
    final dialect = driver.dialect;
    final values = _entity.columnValuesOf(entity);
    final statement = EntityStatements.insert(dialect, _entity, values);
    final result = await _run(statement);
    if (dialect.supportsReturning) {
      if (result.rows.isEmpty) {
        throw QueryExecutionException(
          'The INSERT into "${_entity.table}" returned no row for the $T.',
          sql: statement.sql,
        );
      }
      return _map(result.rows.first);
    }
    final id = values[_entity.idColumn] ?? result.lastInsertId;
    if (id == null) {
      throw QueryExecutionException(
        'The database reported no id for the $T inserted into '
        '"${_entity.table}", so it cannot be read back.',
        sql: statement.sql,
      );
    }
    final stored = await _findById(id);
    if (stored == null) {
      throw QueryExecutionException(
        'The $T inserted into "${_entity.table}" could not be read back by '
        'its id.',
        sql: statement.sql,
      );
    }
    return stored;
  }

  Future<T?> update(T entity) async {
    final values = _entity.columnValuesOf(entity);
    final id = values[_entity.idColumn];
    if (id == null) {
      throw ArgumentError(
        'The id field "${_entity.idField}" of this $T is null, so there is '
            'no row to update; insert it first.',
        'entity',
      );
    }
    if (_entity.columns.length == 1) return _findById(id);
    final dialect = driver.dialect;
    final result =
        await _run(EntityStatements.update(dialect, _entity, values));
    if (dialect.supportsReturning) {
      return result.rows.isEmpty ? null : _map(result.rows.first);
    }
    if (result.affectedRows == 0) return null;
    return _findById(id);
  }

  Future<bool> deleteById(ID id) async {
    final result =
        await _run(EntityStatements.deleteById(driver.dialect, _entity, id));
    return result.affectedRows > 0;
  }

  Future<List<T>> execute(
    String sql, {
    Map<String, Object?>? parameters,
    bool returning = false,
  }) async {
    final result = await driver.query(
      driver.dialect.applyReturning(sql, returning: returning),
      parameters: parameters,
    );
    return _mapAll(result);
  }

  Future<List<T>> find(Query query) {
    final built = query.build(driver.dialect);
    return execute(built.sql, parameters: built.parameters);
  }

  Future<T?> _findById(Object id) async {
    final result =
        await _run(EntityStatements.selectById(driver.dialect, _entity, id));
    return result.rows.isEmpty ? null : _map(result.rows.first);
  }

  Future<QueryResult> _run(BuiltQuery statement) =>
      driver.query(statement.sql, parameters: statement.parameters);

  List<T> _mapAll(QueryResult result) =>
      [for (final row in result.rows) _map(row)];

  T _map(Map<String, Object?> row) {
    final definition = _entity.definition;
    try {
      return definition.fromRow(EntityRow(definition, row)) as T;
    } on MappingException {
      rethrow;
    } catch (error) {
      throw MappingException(
        'Failed to map a row onto $T: $error',
        cause: error,
      );
    }
  }

  EntityMapping _resolve() {
    final manifest = RatelOrmRuntime.installed;
    if (manifest == null) {
      throw StateError(
        'No Ratel ORM entity manifest is installed in this isolate, so '
        '$runtimeType cannot map $T. @Entity mappers are generated by the '
        'ratel CLI: run the app with `ratel dev`, compile it with '
        '`ratel build` and run its tests with `ratel test`; plain '
        '`dart run`, `dart compile exe` and `dart test` skip generation. '
        'In an isolate you spawn yourself, call RatelOrmRuntime.install(...) '
        'with the same manifest first.',
      );
    }
    return EntityCatalog.of(manifest).lookup(T) ??
        (throw StateError(
          '$T is not an @Entity: annotate it with @Entity() and give it an '
          '@Id() field.',
        ));
  }
}
