import 'package:ratel_orm/postgres.dart';
import 'package:ratel_orm/ratel_orm.dart';

abstract final class NoteSchema {
  static Migration migrationFor(RatelDriver driver) => Migration(
        id: '001_notes',
        up: [driver is PostgresDriver ? _postgres : _sqlite],
        down: ['DROP TABLE notes'],
      );

  static const _sqlite = 'CREATE TABLE notes ('
      'id INTEGER PRIMARY KEY, '
      'body TEXT NOT NULL, '
      'created_at TEXT NOT NULL, '
      'pinned INTEGER NOT NULL)';

  static const _postgres = 'CREATE TABLE notes ('
      'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, '
      'body TEXT NOT NULL, '
      'created_at TIMESTAMPTZ NOT NULL, '
      'pinned BOOLEAN NOT NULL)';
}
