import 'package:ratel_orm/runtime.dart';
import 'package:ratel_orm/testing.dart';
import 'package:test/test.dart';

import '../support/fixtures/repositories/widget_repository.dart';

void main() {
  test('a repository refuses to start when no manifest is installed', () {
    expect(RatelOrmRuntime.installed, isNull);
    final driver = FakeDriver();
    expect(
      () => WidgetRepository(driver),
      throwsA(isA<StateError>().having(
        (error) => error.message,
        'message',
        'No Ratel ORM entity manifest is installed in this isolate, so '
            'WidgetRepository cannot map Widget. @Entity mappers are '
            'generated by the ratel CLI: run the app with `ratel dev`, '
            'compile it with `ratel build` and run its tests with '
            '`ratel test`; plain `dart run`, `dart compile exe` and '
            '`dart test` skip generation. In an isolate you spawn yourself, '
            'call RatelOrmRuntime.install(...) with the same manifest first.',
      )),
    );
    expect(driver.lastSql, isNull);
  });
}
